# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_slider_threads_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(601, 417)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        self.cmb_threads = QtWidgets.QComboBox(Dialog)
        self.cmb_threads.setObjectName("cmb_threads")
        self.verticalLayout_4.addWidget(self.cmb_threads)
        self.btn_add_existing = QtWidgets.QPushButton(Dialog)
        self.btn_add_existing.setObjectName("btn_add_existing")
        self.verticalLayout_4.addWidget(self.btn_add_existing)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.chk_high_is_good = QtWidgets.QCheckBox(Dialog)
        self.chk_high_is_good.setEnabled(True)
        self.chk_high_is_good.setChecked(True)
        self.chk_high_is_good.setObjectName("chk_high_is_good")
        self.verticalLayout_4.addWidget(self.chk_high_is_good)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.txt_min_val = QtWidgets.QLineEdit(Dialog)
        self.txt_min_val.setObjectName("txt_min_val")
        self.verticalLayout_5.addWidget(self.txt_min_val)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.txt_max_val = QtWidgets.QLineEdit(Dialog)
        self.txt_max_val.setObjectName("txt_max_val")
        self.verticalLayout_6.addWidget(self.txt_max_val)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.text_entry = QtWidgets.QLineEdit(Dialog)
        self.text_entry.setObjectName("text_entry")
        self.verticalLayout_4.addWidget(self.text_entry)
        self.btn_add_new = QtWidgets.QPushButton(Dialog)
        self.btn_add_new.setObjectName("btn_add_new")
        self.verticalLayout_4.addWidget(self.btn_add_new)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.thread_list = QtWidgets.QListWidget(Dialog)
        self.thread_list.setObjectName("thread_list")
        self.verticalLayout_3.addWidget(self.thread_list)
        self.btn_remove = QtWidgets.QPushButton(Dialog)
        self.btn_remove.setObjectName("btn_remove")
        self.verticalLayout_3.addWidget(self.btn_remove)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_ok = QtWidgets.QPushButton(Dialog)
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout.addWidget(self.btn_ok)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; text-decoration: underline;\">Add Existing:</span></p></body></html>"))
        self.btn_add_existing.setText(_translate("Dialog", "Add Existing"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; text-decoration: underline;\">Add New:</span></p></body></html>"))
        self.chk_high_is_good.setText(_translate("Dialog", "High score is good"))
        self.label_3.setText(_translate("Dialog", "Min Value"))
        self.label_4.setText(_translate("Dialog", "Max Value:"))
        self.label_5.setText(_translate("Dialog", "Name:"))
        self.btn_add_new.setText(_translate("Dialog", "Add New"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; text-decoration: underline;\">Current QuickThreads:</span></p><p align=\"center\">To remove, select entry and press Remove</p></body></html>"))
        self.btn_remove.setText(_translate("Dialog", "Remove"))
        self.btn_ok.setText(_translate("Dialog", "OK"))

