# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(895, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_main.setObjectName("tab_main")
        self.graph = QtWidgets.QWidget()
        self.graph.setObjectName("graph")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.graph)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graph_container = QtWidgets.QVBoxLayout()
        self.graph_container.setObjectName("graph_container")
        self.horizontalLayout.addLayout(self.graph_container)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.graph)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        self.line_year = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_year.sizePolicy().hasHeightForWidth())
        self.line_year.setSizePolicy(sizePolicy)
        self.line_year.setObjectName("line_year")
        self.verticalLayout_4.addWidget(self.line_year, 0, QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.line_month = QtWidgets.QLineEdit(self.frame)
        self.line_month.setObjectName("line_month")
        self.verticalLayout_4.addWidget(self.line_month)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem2)
        self.btn_update_graph = QtWidgets.QPushButton(self.frame)
        self.btn_update_graph.setObjectName("btn_update_graph")
        self.verticalLayout_4.addWidget(self.btn_update_graph)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tab_main.addTab(self.graph, "")
        self.diary = QtWidgets.QWidget()
        self.diary.setObjectName("diary")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.diary)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.diary)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 853, 495))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tab_main.addTab(self.diary, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.tab_main.addTab(self.settings, "")
        self.about = QtWidgets.QWidget()
        self.about.setObjectName("about")
        self.tab_main.addTab(self.about, "")
        self.verticalLayout.addWidget(self.tab_main)
        self.btn_test = QtWidgets.QPushButton(self.centralwidget)
        self.btn_test.setObjectName("btn_test")
        self.verticalLayout.addWidget(self.btn_test)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tab_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HealthThreads"))
        self.label_2.setText(_translate("MainWindow", "Year: "))
        self.label.setText(_translate("MainWindow", "Month:"))
        self.btn_update_graph.setText(_translate("MainWindow", "Show"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.graph), _translate("MainWindow", "Graph"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.diary), _translate("MainWindow", "Diary"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.settings), _translate("MainWindow", "Settings"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.about), _translate("MainWindow", "About"))
        self.btn_test.setText(_translate("MainWindow", "QuickThreads"))

