# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(895, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_main.setObjectName("tab_main")
        self.graph = QtWidgets.QWidget()
        self.graph.setObjectName("graph")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.graph)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graph_container = QtWidgets.QVBoxLayout()
        self.graph_container.setObjectName("graph_container")
        self.horizontalLayout.addLayout(self.graph_container)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.graph)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        self.line_year = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_year.sizePolicy().hasHeightForWidth())
        self.line_year.setSizePolicy(sizePolicy)
        self.line_year.setObjectName("line_year")
        self.verticalLayout_4.addWidget(self.line_year, 0, QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.line_month = QtWidgets.QLineEdit(self.frame)
        self.line_month.setObjectName("line_month")
        self.verticalLayout_4.addWidget(self.line_month)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem2)
        self.btn_update_graph = QtWidgets.QPushButton(self.frame)
        self.btn_update_graph.setObjectName("btn_update_graph")
        self.verticalLayout_4.addWidget(self.btn_update_graph)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tab_main.addTab(self.graph, "")
        self.diary = QtWidgets.QWidget()
        self.diary.setObjectName("diary")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.diary)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.diary)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.line_diary_year = QtWidgets.QLineEdit(self.diary)
        self.line_diary_year.setObjectName("line_diary_year")
        self.horizontalLayout_2.addWidget(self.line_diary_year)
        self.label_3 = QtWidgets.QLabel(self.diary)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.line_diary_month = QtWidgets.QLineEdit(self.diary)
        self.line_diary_month.setObjectName("line_diary_month")
        self.horizontalLayout_2.addWidget(self.line_diary_month)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.btn_diary_update = QtWidgets.QPushButton(self.diary)
        self.btn_diary_update.setObjectName("btn_diary_update")
        self.verticalLayout_2.addWidget(self.btn_diary_update)
        self.line = QtWidgets.QFrame(self.diary)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.scrollArea = QtWidgets.QScrollArea(self.diary)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 853, 414))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.diary_text = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.diary_text.setObjectName("diary_text")
        self.verticalLayout_5.addWidget(self.diary_text)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.btn_new_diary_entry = QtWidgets.QPushButton(self.diary)
        self.btn_new_diary_entry.setObjectName("btn_new_diary_entry")
        self.verticalLayout_2.addWidget(self.btn_new_diary_entry)
        self.tab_main.addTab(self.diary, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.tab_main.addTab(self.settings, "")
        self.about = QtWidgets.QWidget()
        self.about.setObjectName("about")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.about)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.about)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.tab_main.addTab(self.about, "")
        self.verticalLayout.addWidget(self.tab_main)
        self.btn_test = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_test.sizePolicy().hasHeightForWidth())
        self.btn_test.setSizePolicy(sizePolicy)
        self.btn_test.setObjectName("btn_test")
        self.verticalLayout.addWidget(self.btn_test, 0, QtCore.Qt.AlignRight)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tab_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HealthThreads"))
        self.label_2.setText(_translate("MainWindow", "Year: "))
        self.label.setText(_translate("MainWindow", "Month:"))
        self.btn_update_graph.setText(_translate("MainWindow", "Show"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.graph), _translate("MainWindow", "Graph"))
        self.label_4.setText(_translate("MainWindow", "Year"))
        self.label_3.setText(_translate("MainWindow", "Month"))
        self.btn_diary_update.setText(_translate("MainWindow", "Show"))
        self.btn_new_diary_entry.setText(_translate("MainWindow", "New Diary Entry"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.diary), _translate("MainWindow", "Diary"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.settings), _translate("MainWindow", "Settings"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">HealthThreads</span> is a program to help you and your doctor manage</p><p align=\"center\">your health and medication. Moreover, it is a useful tool to help</p><p align=\"center\">you set and keep track of personal goals such as diet and</p><p align=\"center\">exercise, and monitor their effect on your wellbeing.</p><p align=\"center\"><br/></p><p align=\"center\">This is a prototype inteded to explore and refine eventual features.</p><p align=\"center\"><br/></p><p align=\"center\">Copyright Oleg Petelin 2016</p></body></html>"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.about), _translate("MainWindow", "About"))
        self.btn_test.setText(_translate("MainWindow", "QuickThreads"))

